"""
frames.py — Tipos de frame que fluem pelo pipeline LVP.

Frames são pacotes imutáveis (dataclasses) que passam de processor em processor.
Dois sentidos:
  - DOWNSTREAM (mic → speaker): áudio entra, vira texto, vira resposta, vira áudio
  - UPSTREAM (speaker → mic): controle, interrupção (barge-in tem prioridade)

System frames (InterruptionFrame, EndFrame) são tratados na hora, fora da fila normal.
"""

from dataclasses import dataclass, field
import time


@dataclass
class Frame:
    """Base. Todo frame carrega timestamp de criação pra medir latência."""
    ts: float = field(default_factory=time.time, kw_only=True)


@dataclass
class SystemFrame(Frame):
    """
    High-priority frame: handled IMMEDIATELY, never queued, survives interruption.
    Interruption/Cancel/End/Error are system frames — they must reach every processor
    instantly even if the data path is busy. This is what keeps barge-in snappy.
    """
    pass


@dataclass
class DataFrame(Frame):
    """Ordered payload (audio/text/transcription). Cancelled by user interruption."""
    pass


# ─── Áudio ───────────────────────────────────────────────────────────

@dataclass
class AudioInFrame(Frame):
    """PCM int16 mono vindo do mic (16kHz). Bytes crus."""
    pcm: bytes = b''
    sample_rate: int = 16000


@dataclass
class AudioOutFrame(Frame):
    """PCM int16 mono pra tocar no speaker (24kHz)."""
    pcm: bytes = b''
    sample_rate: int = 24000
    text: str = ''  # texto que originou esse áudio (debug)


# ─── Vision / multimodal ─────────────────────────────────────────────

@dataclass
class InputImageFrame(DataFrame):
    """An image from the client (camera/screen) — for multimodal/omni LLMs."""
    image: bytes = b''
    fmt: str = 'jpeg'         # jpeg | png
    width: int = 0
    height: int = 0


@dataclass
class UserImageFrame(InputImageFrame):
    """An image explicitly attached to the current user turn."""
    pass


@dataclass
class OutputImageFrame(DataFrame):
    """An image generated by the bot (e.g. image-gen tool)."""
    image: bytes = b''
    fmt: str = 'png'


@dataclass
class VisionTextFrame(DataFrame):
    """Text describing/answering about an image (vision model output)."""
    text: str = ''


# ─── VAD / turn detection ────────────────────────────────────────────

@dataclass
class UserStartedSpeakingFrame(Frame):
    """VAD detectou início de fala."""
    pass


@dataclass
class PartialUtteranceFrame(Frame):
    """Áudio parcial enquanto o user AINDA fala — pra STT transcrever interim (streaming)."""
    audio_wav: bytes = b''
    duration_ms: int = 0


@dataclass
class UserStoppedSpeakingFrame(Frame):
    """VAD detectou fim de fala (silêncio > threshold). Carrega o áudio acumulado."""
    audio_wav: bytes = b''
    duration_ms: int = 0


# ─── STT ─────────────────────────────────────────────────────────────

@dataclass
class InterimTranscriptionFrame(Frame):
    """Transcrição PARCIAL (enquanto user ainda fala). Pode mudar."""
    text: str = ''


@dataclass
class TranscriptionFrame(Frame):
    """Transcrição FINAL (após fim da fala)."""
    text: str = ''
    # Optional per-word timing from the STT (list of {"word","start","end"} in seconds).
    # Empty unless the STT backend returns word-level timestamps.
    words: list = field(default_factory=list)


@dataclass
class WordTimestampFrame(Frame):
    """
    A single spoken word aligned to the bot's output audio timeline (karaoke/highlight).
    Emitted by TTS backends that report word timing; `time` is seconds from the start of
    the current utterance.
    """
    word: str = ''
    time: float = 0.0


@dataclass
class TranscriptionUpdateFrame(Frame):
    """
    A newly appended conversation message {role, content, ts}, emitted by the
    TranscriptProcessor whenever the running transcript grows. For UI/logging/audit.
    """
    role: str = ''
    content: str = ''
    at: float = 0.0


# ─── LLM ─────────────────────────────────────────────────────────────

@dataclass
class LLMTokenFrame(Frame):
    """Um token (ou pedaço) gerado pelo LLM em streaming."""
    text: str = ''


@dataclass
class LLMFullResponseFrame(Frame):
    """Resposta completa do LLM (fim do turno)."""
    text: str = ''


@dataclass
class TextSentenceFrame(Frame):
    """Uma sentença completa pronta pra TTS (saída do SentenceAggregator)."""
    text: str = ''


@dataclass
class FunctionCallFrame(Frame):
    """LLM pediu pra executar uma tool."""
    tool_call_id: str = ''
    name: str = ''
    args: dict = field(default_factory=dict)


@dataclass
class FunctionCallResultFrame(Frame):
    """Resultado de uma tool, pronto pra voltar ao contexto."""
    tool_call_id: str = ''
    name: str = ''
    result: object = None


# ─── Controle / sistema (prioridade alta) ────────────────────────────

@dataclass
class ControlFrame(Frame):
    """Frame de controle genérico (config, comandos)."""
    action: str = ''
    data: dict = field(default_factory=dict)


@dataclass
class InterruptionFrame(SystemFrame):
    """Barge-in: user falou em cima do Astro. Cancela TUDO downstream imediatamente."""
    pass


@dataclass
class CancelFrame(SystemFrame):
    """Encerra a sessão imediatamente, sem drenar (diferente de EndFrame que faz cleanup)."""
    pass


@dataclass
class InputDTMFFrame(SystemFrame):
    """A DTMF key press from the caller (telephony)."""
    digit: str = ''


@dataclass
class OutputDTMFFrame(SystemFrame):
    """A DTMF tone to play to the caller (telephony)."""
    digit: str = ''


@dataclass
class MetricsFrame(Frame):
    """Latency/usage metrics for a turn (TTFB per stage, totals)."""
    metrics: dict = field(default_factory=dict)


@dataclass
class ErrorFrame(SystemFrame):
    """Erro em algum processor."""
    message: str = ''
    source: str = ''


@dataclass
class EndFrame(SystemFrame):
    """Fim da sessão. Cada processor faz cleanup."""
    pass


@dataclass
class StartFrame(SystemFrame):
    """Boot: propaga config (sample rates, flags) por todo o pipeline no início."""
    sample_rate_in: int = 16000
    sample_rate_out: int = 24000
    enable_metrics: bool = True
    data: dict = field(default_factory=dict)


@dataclass
class HeartbeatFrame(SystemFrame):
    """Pulso periódico — mede saúde/latência do pipeline (detecta travamento)."""
    seq: int = 0


@dataclass
class TTSStartedFrame(SystemFrame):
    """O bot começou a falar (primeiro chunk de áudio de uma resposta)."""
    pass


@dataclass
class TTSStoppedFrame(SystemFrame):
    """O bot terminou de falar."""
    pass


@dataclass
class PauseFrame(SystemFrame):
    """Pausa o processamento de data frames num processor (system frames continuam)."""
    target: str = ''   # nome do processor; '' = todos


@dataclass
class ResumeFrame(SystemFrame):
    """Retoma o processamento pausado."""
    target: str = ''
